lst=[3,45,92,43,68,72,84,449]
print(type(lst),id(lst),lst)

print()

size=len(lst)
print("No. of elements :",size)
lst.append(81)
print(type(lst),id(lst),lst)
lst.remove(45)
print(type(lst),id(lst),lst)
index=lst.index(43)
print("Index of 43 : ",index)
count=lst.count(43)
print("Count of 43 : ",count)
copy=lst.copy()
print("copy of list",copy)
blst=[22,33,65,98]
lst.extend(blst)
print('extended list:',lst)
lst.insert(3,20)
print('after insertion:',lst)
lst.pop()
print('list after popping last element:',lst)
lst.pop(3)
print("list after popping 3rd indexed element",lst)
lst.reverse()
print("reverse the list",lst)
lst.remove(27)
print("after removing 27:",lst)
lst.sort()
print("sorted list:",lst)
lst.clear()
print("after clearing:",lst)

