f=open('example.txt','r')
print(' file name:',f.name)
print(' file mode:',f.mode)
print(' is file readable ?',f.readable())
print(' is file writeable ?',f.writable())
print(' is file closed ?',f.closed)
f.close()
print(' is file closed ?',f.closed)